typography_spectrum: 0.975074807414785
color:
  brandStrength: 0.4906522915698588
  lightness: 0.622172690462321
  saturation: 0.7134183596353978
  rhythmicContrast: 0.943070640321821
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
layout_spectrum: 0.10960364411585033
name: Sick Swallow
navigation:
  - name: Auctionsfind
    url: 'http://www.auctionsfind.com/main'
    type: external
  - name: Google May Have Found a Way to Make the Real-World Web Work
    id: eb2ce4bf-4369-4a2d-8385-eb68196ddb25
    type: content
title: A Way to the Park
description: Just Sit Back and Watch
